### PR TITLE
zh-cn Localization

### PR DESCRIPTION
**Pull request by GreyElaina**

### CODE REVIEW

**Comment by GreyElaina** [comment]
oops.

**Comment by sena-nana** [comment]
The translation is not yet complete. Sorry for the mistake.

**Comment by KotlinIsland** [comment]
Happy for this PR to exist as a draft

**Comment by GreyElaina** [comment]
> Happy for this PR to exist as a draft

this branch is wrong, should be merged from sena-nana:main not elaina.

**Comment by KotlinIsland** [comment]
> this branch is wrong, should be merged from sena-nana:main not elaina.

Don't worry, this is Githubs UX issue. It has happened to us many many times.... 😅

**Pull request closed without merging**
