### PR TITLE
use bun instead of node

### LINKED ISSUE #60: investigate bun
it might make pyright faster

### PR DESCRIPTION
**Pull request by DetachHead**
fixes #60 

potentially also fixes these issues - need to confirm with the people who raised them:
- #177 
- #172
- #167

### CODE REVIEW

**Comment by divaltor** [comment]
There are any performance benchmarks for that replacement?

**Comment by DetachHead** [comment]
i measured how long it took to run pyright 100 times with both node and bun and it was only a few seconds faster lol. the main reason i wanted to try this was to see if it would fix any of the issues people had with the bundled node, but tbh it will probably cause more problems than it'll solve. can't even get `bun install` to work

**Comment by divaltor** [comment]
Few seconds still is nice. Would be nice to see more detailed benchmark with `hyperfine` or similar tool. Good job

**Comment by DetachHead** [comment]
all of the issues mentioned in the OP have been resolved (except #177 which is just pending some documentation), so i don't really see much point in doing this anymore, especially since there was pretty much no performance gains. can re-visit in the future if that changes

**Pull request closed without merging**
