### PR TITLE
Chinese translations fix

### PR DESCRIPTION
**Pull request by sena-nana**
This is about fixing the Chinese translation. pyright's original Chinese translation had a lot of holes in it, so it's been tweaked in this PR.

The people involved in the translation are not professional localizers, so it's basically a work in progress according to our personal habits.

Most of the translations were done by NCBM and GreyElaina.I just completed the documentation.Thanks for their help.

### CODE REVIEW

**Review by DetachHead — APPROVED** [review]

**Comment by NCBM** [comment]
After that, we will continue to follow up on the changes of the translated text, and after a certain number of changes of the translated text have accumulated, we will initiate a new Pull Request to submit new translated texts.

**Comment by DetachHead** [comment]
thanks! i want to merge this soon but might get someone else to review it first

**Comment by NCBM** [comment]
OK. We are generally ready now.

**Comment by DetachHead** [comment]
thanks!

**Pull request merged**
