### PR TITLE
Fix some broken `docs/` links

### PR DESCRIPTION
**Pull request by LV**
As per 4543af4042f942eb91a3e5ea5976b4ee0141bb2b, `docs/configuration/config-files.md` was moved to `docs/configuration.md`. However, a link in `docs/configuration/language-server-settings.md` still points to this old document.

EDIT: Found a lot of broken links, will continue to commit as I encounter them.

### CODE REVIEW

**Comment by LV** [comment]
This is as far as I'll go for now as I have to get back to work 😛

Happy to help out with the rest of the links if you need it, I'll just need to fix these later in the day.

**Comment by DetachHead** [comment]
these links are broken when viewing the docs on github because the file is moved to a different location when building the docs site ([see the comment here](https://github.com/DetachHead/basedpyright/blob/main/docs/configuration/config-files.md?plain=1))

if you look at the documentation on [docs.basedpyright.com](https://docs.basedpyright.com/latest/configuration/config-files/) they work

**Comment by LV** [comment]
Oof, I didn't even realize there was a webpage. I apologize. Guess this can be closed right?

**Comment by DetachHead** [comment]
all good. i agree its confusing. i should probably just move the page back to its actual location at some point in the future when it's less likely that there are still people using those older versions of basedpyright

**Pull request closed without merging**
