### PR TITLE
attempt at pycharm plugin

### LINKED ISSUE #27: pycharm plugin

### PR DESCRIPTION
**Pull request by DetachHead**
fixes #27 

currently doesn't work and i don't really have the time or patience to spend more time working on a plugin for an IDE i don't use anymore so if any pycharm user wants to have a go at finishing this PR that would be appreciated. 

keep in mind that jetbrains are against language server protocol so their support for it is quite half-assed and [is only available on paid versions of their IDEs](https://blog.jetbrains.com/platform/2023/07/lsp-for-plugin-developers/#supported-ides). so i decided to try using [lsp4intellij](https://github.com/ballerina-platform/lsp4intellij) instead so that pycharm community users don't miss out, but i couldn't get it to work. but if anybody can get it working either with that or the official paid LSP support i'd still be happy to merge it because it's better than nothing

### CODE REVIEW

**Comment by angelozerr** [comment]
@DetachHead please try https://github.com/redhat-developer/lsp4ij which is a free LSP support plugin for Intellij.

**Comment by DetachHead** [comment]
@angelozerr thanks, this plugin looks promising. however i can't seem to get it to work, so i raised a few issues:

- https://github.com/redhat-developer/lsp4ij/issues/336
- https://github.com/redhat-developer/lsp4ij/issues/337
- https://github.com/redhat-developer/lsp4ij/issues/338

**Comment by DetachHead** [comment]
would be nice if someone more experienced with intellij/gradle than me could take over this PR now that we have a decent LSP client we can use. i cannot stand working with gradle

**Comment by DetachHead** [comment]
closing this as the current pyright pycharm plugin works well with basedpyright

**Comment by beauxq** [comment]
Is this up-to-date with what works well?
https://github.com/DetachHead/basedpyright/blob/main/docs/installation.md#pycharm

**Comment by DetachHead** [comment]
as far as im aware those instructions are still accurate

**Pull request closed without merging**
