### PR TITLE
No bounds if type param present

### PR DESCRIPTION
**Pull request by beauxq**
This is a pull request onto the narrowing generics branch, not onto main.

And I've pulled from current main here, so if you pull from main on that target branch, it will clean up the diff here.

---

This fixes the test case that was failing, and also https://github.com/DetachHead/basedpyright/pull/745#discussion_r1831126997 (which were really the same issue).

And also changes to use this new narrowing on `Any` and `Unknown` as discussed in https://github.com/DetachHead/basedpyright/pull/745#discussion_r1845286687

It also adds a few more test cases.

### CODE REVIEW

**Comment by DetachHead** [comment]
awesome thanks! will take a look at this later today. i assumed the fix would be very difficult but i guess it was something simple i was missing 

do you mind removing the upstream commits? i only do upstream merges when there's a new release. or if it's too much of a hassle i can do that myself

**Comment by beauxq** [comment]
I think I only pulled from basedpyright main, not from pyright.
That's the "pull from main" I'm talking about.

Your branch in https://github.com/DetachHead/basedpyright/pull/745 was a month old.

**Comment by DetachHead** [comment]
ah i see, all good then

**Comment by DetachHead** [comment]
i've cherrypicked your commits into #745 and rebased onto main. the primer identified an issue with constrained typevars (https://github.com/DetachHead/basedpyright/pull/745#issuecomment-2482982482). i dont think it'd be too hard to fix, i'll try to look into it within the next couple days, but if you'd rather give it a go feel free

thanks again for the help!

**Comment by DetachHead** [comment]
closing this since i've merged your commits into #745 and fixed the issue with constraints

**Pull request closed without merging**
