### PR TITLE
Fetch config from clients in different order.

### LINKED ISSUE #894: document how to configure language server settings in eglot
I've been trying to use `basedpyright` (version `1.21.1`), but I cannot configure any of the `analysis` settings. I'm using `eglot` and this is the result of `eglot-show-workspace-configuration`:

```
{
  "basedpyright": {
    "typeCheckingMode": "recommended",
    "analysis": {
      "diagnosticSeverityOverrides": {
        "reportUnusedCallResult": false,
        "reportInvalidCast": false
      },
      "inlayHints": {
        "callArgumentNames": false,
        "functionReturnTypes": false,
        "variableTypes": false,
        "genericTypes": false
      }
    }
  },
  "python": {
    "pythonPath": "/nix/store/sc8hbm8i8n22f5f7wrf2dla333bdwpri-env-default/bin/python",
    "venvPath": null
  }
}
```

Still, I keep on seeing `reportUnusedCallResult` pop up all over the code. I'm reasonably confident that `eglot` is sending the configuration because if I change `typeCheckingMode` to `"basic"` or `"off"` I see a difference. I also keep on seeing inlay hints, even though I much rather not see them. This leads me to believe my `basedpyright-langserver` is not really respecting the settings under `analysis`. 

I did try a number of variations, adding a `"settings"` section; moving the `"analysis"` section to the top-level as if it was in a `pyrightconfig.json` file; etc... but I had no success so far. Am I doing something obviously wrong here?

I'm not really sure wheter to ask for help in the `eglot` repo or here. Decided to start here because I can get `basedpyright` to obey the `typeCheckingMode` setting, which suggests `eglot` is not at fault. 

Thank you!

### PR DESCRIPTION
**Pull request by VictorCMiraldo**
Closes #894: Fetch the `basedpyright` section before trying to
fetch `basedpyright.analysis`, since we might have received the `analysis` settings in the first go anyway. In fact, only ask the client for `basedpyright.analysis` if we haven't received in the first request.

I know zero typescript, I also don't know how to run the server to test my changes. Any advice there?

### CODE REVIEW

**Comment by DetachHead** [comment]
thanks. i'll try to get around to looking at this within the next few days.

> I know zero typescript, I also don't know how to run the server to test my changes. Any advice there?

the typescript/nodejs installation is managed by [uv](https://docs.astral.sh/uv/) using [nodejs-wheel](https://github.com/njzjz/nodejs-wheel) so you don't have to install anything extra as long as you already have python installed. just run `./pw uv sync` which will install all the dependencies to your venv and build the project.

the easiest way to test the language server IMO is with vscode, there's a debug config set up that will automatically launch a separate vscode instance with the extension installed:

image

if you just want to build the language server so you can run it with eglot, as long as eglot doesn't use its own bundled version of the language server, you should be able to just activate the venv and launch emacs from inside it. note that when running the language server this way will probably require you to re-install the project every time you make any changes to the code:

```
./pw uv sync --reinstall-package basedpyright
```

(i haven't tried debugging the language server this way so i can't guarantee it'll work, but i'll try to assist if you run into any issue)

you may also want to use some of the predefined scripts in [`package.json`](https://github.com/DetachHead/basedpyright/blob/main/package.json). you can run them inside your venv using `npm run commandname` eg:

```
npm run typecheck
```

see [the contributing docs](https://docs.basedpyright.com/latest/development/contributing/) for more info

**Comment by VictorCMiraldo** [comment]
I managed to build and use the server; I'll hopefully have time on the weekend to tinker with this a little more! :+1:

**Comment by DetachHead** [comment]
hey, so i looked into this and i think i figured out a fix that should work for both vscode and eglot. see #920

would you mind testing it out and let me know if it works? thanks

**Comment by VictorCMiraldo** [comment]
I'll close this PR; given we found a reliable way to configure `eglot` (which, btw, is the same as zed, who also requires a `basedpyright.analysis`-named section), I'll close this in favor of just documenting the behavior:

https://github.com/DetachHead/basedpyright/pull/935

**Pull request closed without merging**
