### PR TITLE
Fix `Unknown` and `Any` variables being coloured as Unbound

### LINKED ISSUE #180: variables with "Unknown" & `Any` types are coloured as unbound
image

### PR DESCRIPTION
**Pull request by ValdezFOmar**
Fixes #180

### CODE REVIEW

**Comment by ValdezFOmar** [comment]
I noticed that `Any` is being coloured as a variable instead of a type and that is already an open issue (#150). Looking at how is defined in `typeshed` makes sense that it would be coloured this way, but is really odd that they decided to do is in the first place.

https://github.com/DetachHead/basedpyright/blob/b1ebff9e96a087851fc24efe1674660cfea59140/packages/pyright-internal/typeshed-fallback/stdlib/typing.pyi#L138

**Comment by DetachHead** [comment]
> I noticed that `Any` is being coloured as a variable instead of a type and that is already an open issue (#150). Looking at how is defined in `typeshed` makes sense that it would be coloured this way, but is really odd that they decided to do is in the first place.
> 
> https://github.com/DetachHead/basedpyright/blob/b1ebff9e96a087851fc24efe1674660cfea59140/packages/pyright-internal/typeshed-fallback/stdlib/typing.pyi#L138

yeah that's really weird. @KotlinIsland any idea what's up with that? should we just change it to `_SpecialForm` to match the others?

**Review by DetachHead — APPROVED** [review]

**Comment by KotlinIsland** [comment]
Yeah, it's bizarre how they wrote `typing.pyi`, we could try changing it to `_SpecialForm` and see if it breaks anything.

Supprisingly, it looks like it's already special-cased to some extent:
```py
from typing import Any

reveal_type(Any)  # Type of "Any" is "Any"
```

**Comment by KotlinIsland** [comment]
- #236

**Pull request merged**
